spring.application.name=backend

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/artFinder
spring.datasource.username=postgres
spring.datasource.password=rootroot
spring.datasource.driver-class-name=org.postgresql.Driver

# MyBatis
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=lx.team2.backend.feature.**

# Web resource cache off (???)
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.chain.enabled=false

# Spring Security
spring.security.user.name=1
spring.security.user.password=1